# Generated by Django 4.2.1 on 2023-08-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_followc_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followc',
        ),
    ]
