# Generated by Django 4.2.1 on 2023-08-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_profile',
        ),
    ]
